### ISSUE TITLE
conform.nvim deprecation warning

### ISSUE THREAD

**Issue by richardsc** [dankelley/nvim#2]
Hi!

I was getting a warning when formatting, as in the screenshot below, and it took me a while to figure out how to make it go away.
<img width="797" alt="image" src="https://github.com/user-attachments/assets/5d88aa3a-e410-4fe6-9e93-fed5127f47a6">
I copied the relevant section from [here](https://www.lazyvim.org/plugins/formatting), but just keeping the bare minimum to be able to set the timeout. The resulting `formatter.lua` looks like this:

```lua
return {
    -- increasing formatting time limit to 60 seconds
    -- see https://github.com/LazyVim/LazyVim/issues/51
    {
        "stevearc/conform.nvim",
        opts = function()
            local opts = {
                default_format_opts = {
                    timeout_ms = 60000,
                    async = false,           -- not recommended to change
                    quiet = false,           -- not recommended to change
                    lsp_format = "fallback", -- not recommended to change
                },
            }
            return opts
        end,
    },
}
```
After restarting nvim the formatting works without warnings!

**Comment by dankelley** [comment]
BRILLIANT!  That was bugging me, but not enough to make me search. (unlike issue #3 which I'm about to submit)
